image: gcc:6

build:
  stage: build
  script: 
    - make
  artifacts:
    paths:
      - zad1
      - zad2
      - zad3
      - zad4
      - zad5

test:
  stage: test
  script:
    - ./test-compilation.sh
    - ./test-fail.sh
    - ./test-runtime.sh
