sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
install:
- [ "$CXX" = "g++" ] && export CXX="g++-6" CC="gcc-6"
script:
  - make
  - make test
