sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
install:
- "[ $CXX = g++ ] && export CXX=g++-6"
script:
  - make
  - make test
